version: "2.1"
services:
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
    ports:
      - '7878:7878'
    volumes:
      - /media/HDD1/server/configs/radarr:/config
      - /media/HDD1/server:/data
    restart: unless-stopped
