version: "2.1"
services:
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
    ports:
      - '7878:7878'
    volumes:
      - "D:/server/configs/radarr:/config"
      - "D:/server:/data"
    restart: unless-stopped
