version: "2.1"
services:
  jellyfin:
    container_name: jellyfin
    image: ghcr.io/linuxserver/jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
    ports:
      - '8096:8096'
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    volumes:
      - /media/HDD1/server/configs/jellyfin:/config
      - /media/HDD1/server/media/tv:/data/tvshows
      - /media/HDD1/server/media/movies:/data/movies
    restart: unless-stopped
