version: "2.1"
services:
  heimdall:
    container_name: heimdall
    image: ghcr.io/linuxserver/heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
    volumes:
      - /media/HDD1/server/configs/heimdall:/config
    ports:
      - 8090:80
    restart: unless-stopped
